steps:
  - id: Build
    name: gcr.io/cloud-builders/docker
    args:
      - build
      - --no-cache
      - -t
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/explicabilidad-api:$BUILD_ID
      - -f
      - app/Dockerfile
      - .
  - id: Push
    name: gcr.io/cloud-builders/docker
    args:
      - push
      - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/explicabilidad-api:$BUILD_ID
  - id: Deploy
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    entrypoint: gcloud
    args:
      - run
      - services
      - update
      - explicabilidad-api
      - --platform=managed
      - --image=us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/explicabilidad-api:$BUILD_ID
      - --region=us-central1
      - --memory=2Gi
      - --cpu=2
      - --timeout=300
      - --set-env-vars=GCP_PROJECT_ID=$PROJECT_ID,GCP_LOCATION=us-central1,GEMINI_MODEL=gemini-2.5-flash,CONVERTER_BACKEND=cloudbuild,GCS_BUCKET=$PROJECT_ID-explicabilidad-xai,CORS_ORIGINS=https://explicabilidad-frontend-92911726008.us-central1.run.app
      - --set-secrets=API_KEY=explicabilidad-api-key:latest,GEMINI_API_KEY=explicabilidad-gemini-api-key:latest
      - --quiet
images:
  - us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/explicabilidad-api:$BUILD_ID
options:
  logging: CLOUD_LOGGING_ONLY
